import { useEffect, useMemo, useState } from "react";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { ExternalLink, RefreshCw, Search, Star, ShieldAlert, Activity, ArrowUpRight, SlidersHorizontal, Info } from "lucide-react";
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip";
import type { RadarToken } from "../../../server/marketData";

const money = new Intl.NumberFormat("en-US", { notation: "compact", maximumFractionDigits: 1 });
const price = new Intl.NumberFormat("en-US", { maximumSignificantDigits: 5 });
const ageLabel = (minutes: number) => minutes < 60 ? `${minutes} phút` : minutes < 1440 ? `${Math.floor(minutes / 60)} giờ` : `${Math.floor(minutes / 1440)} ngày`;

function scoreTone(score: number, inverse = false) {
  const positive = inverse ? score < 35 : score >= 65;
  return positive ? "text-emerald-700 bg-emerald-50 border-emerald-200" : score >= 45 ? "text-amber-700 bg-amber-50 border-amber-200" : "text-rose-700 bg-rose-50 border-rose-200";
}

export default function Home() {
  const [search, setSearch] = useState("");
  const [chain, setChain] = useState("all");
  const [sort, setSort] = useState<"potential" | "age" | "liquidity" | "volume" | "momentum" | "risk">("potential");
  const [minVolume, setMinVolume] = useState(0);
  const [maxVolume, setMaxVolume] = useState(0);
  const [sparklineRange, setSparklineRange] = useState<"1h" | "4h" | "24h">("24h");
  const [selected, setSelected] = useState<RadarToken | null>(null);
  const [watchlist, setWatchlist] = useState<string[]>(() => JSON.parse(localStorage.getItem("memecoin-radar-watchlist") ?? "[]"));
  const [threshold, setThreshold] = useState(() => Number(localStorage.getItem("memecoin-radar-threshold") ?? 70));
  const input = useMemo(() => ({ search: search || undefined, chain, sort, minVolume24h: minVolume || undefined, maxVolume24h: maxVolume || undefined, sparklineRange, limit: 18 }), [search, chain, sort, minVolume, maxVolume, sparklineRange]);
  const query = trpc.tokens.discover.useQuery(input, { refetchInterval: 120000 });
  const tokens = query.data?.tokens ?? [];
  const thresholdHits = tokens.filter(t => t.potentialScore >= threshold).length;
  const [alertMessage, setAlertMessage] = useState("");
  useEffect(() => {
    const hit = tokens.find(t => t.potentialScore >= threshold || (watchlist.includes(t.id) && t.riskScore >= 75));
    if (hit) setAlertMessage(hit.potentialScore >= threshold ? `${hit.symbol} đã vượt ngưỡng tiềm năng (${hit.potentialScore})` : `${hit.symbol} nhận cảnh báo rủi ro cao (${hit.riskScore})`);
  }, [tokens, threshold, watchlist]);

  const toggleWatch = (id: string) => setWatchlist(current => { const next = current.includes(id) ? current.filter(x => x !== id) : [...current, id]; localStorage.setItem("memecoin-radar-watchlist", JSON.stringify(next)); return next; });
  const updateThreshold = (value: number) => { const next = Math.max(0, Math.min(100, value)); setThreshold(next); localStorage.setItem("memecoin-radar-threshold", String(next)); };

  return <div className="min-h-screen bg-[#f8fafb] text-slate-950">
    <header className="border-b border-slate-900/10 bg-white/85 backdrop-blur sticky top-0 z-20"><div className="max-w-[1440px] mx-auto px-5 lg:px-10 h-20 flex items-center justify-between gap-6"><div className="flex items-center gap-4"><div className="size-11 border-2 border-slate-950 grid place-items-center bg-cyan-100"><span className="font-mono font-bold">MR</span></div><div><p className="font-mono text-[10px] tracking-[0.24em] uppercase text-slate-500">Thiết bị nghiên cứu / 01</p><h1 className="text-xl font-black tracking-tight">MEMECOIN RADAR</h1></div></div><div className="flex items-center gap-3"><div className="hidden md:flex items-center gap-2 font-mono text-xs text-slate-500"><span className="size-2 bg-emerald-500 rounded-full animate-pulse" />LUỒNG DỮ LIỆU CÔNG KHAI</div><Button variant="outline" onClick={() => query.refetch()} disabled={query.isFetching} className="font-mono text-xs"><RefreshCw className={query.isFetching ? "animate-spin mr-2 size-4" : "mr-2 size-4"}/> Làm mới</Button></div></div></header>
    <main className="max-w-[1440px] mx-auto px-5 lg:px-10 py-8 relative"><div className="blueprint-crosshair one"/><div className="blueprint-crosshair two"/>
      <section className="grid lg:grid-cols-[1.15fr_.85fr] gap-8 items-end mb-10"><div><p className="font-mono text-xs text-pink-600 mb-4">// GIAO THỨC DÒ CẶP MỚI</p><h2 className="text-5xl md:text-7xl font-black leading-[.9] tracking-[-.06em] max-w-3xl">Tìm tín hiệu.<br/><span className="text-cyan-500">Thấy rõ rủi ro.</span></h2></div><div className="border-l-2 border-slate-950 pl-5 pb-1 max-w-md"><p className="font-mono text-sm leading-6 text-slate-600">Không gian nghiên cứu minh bạch cho các cặp memecoin mới tạo. Không giao dịch. Không điểm số ẩn. Mọi tín hiệu đều có lý do hiển thị.</p><p className="font-mono text-[10px] uppercase tracking-widest text-slate-400 mt-4">Lần quét cuối: {query.data?.fetchedAt ? new Date(query.data.fetchedAt).toLocaleTimeString() : "đang chờ"}</p></div></section>
      <section className="grid grid-cols-2 lg:grid-cols-4 gap-3 mb-8"><Stat label="Cặp đã lập chỉ mục" value={String(tokens.length).padStart(2, "0")} accent="cyan"/><Stat label="Vượt ngưỡng" value={String(thresholdHits).padStart(2, "0")} accent="pink"/><Stat label="Danh sách theo dõi" value={String(watchlist.length).padStart(2, "0")} accent="lime"/><Stat label="Ngưỡng điểm" value={`${threshold}`} accent="slate"/></section>
      {query.data?.warning && <div className="mb-5 border border-amber-300 bg-amber-50 p-4 font-mono text-xs text-amber-900">THÔNG BÁO DỮ LIỆU: {query.data.warning}. Dashboard hiển thị trạng thái trống thay vì tạo dữ liệu giả.</div>}
      {alertMessage && <div className="mb-5 flex items-center justify-between gap-3 border border-pink-300 bg-pink-50 p-4 font-mono text-xs text-pink-900"><span>CẢNH BÁO / {alertMessage}</span><button onClick={() => setAlertMessage("")} className="text-pink-600">ĐÓNG ×</button></div>}
      <section className="flex flex-col xl:flex-row gap-3 mb-5"><div className="relative flex-1"><Search className="absolute left-3 top-3 size-4 text-slate-400"/><Input value={search} onChange={e => setSearch(e.target.value)} placeholder="Tìm mã, tên token hoặc chain..." className="pl-9 bg-white border-slate-300 font-mono text-xs h-10"/></div><select value={chain} onChange={e => setChain(e.target.value)} className="h-10 border border-slate-300 bg-white px-3 font-mono text-xs"><option value="all">TẤT CẢ CHAIN</option><option value="solana">SOLANA</option><option value="ethereum">ETHEREUM</option><option value="base">BASE</option><option value="bsc">BNB CHAIN</option></select><select value={sort} onChange={e => setSort(e.target.value as typeof sort)} className="h-10 border border-slate-300 bg-white px-3 font-mono text-xs"><option value="potential">SẮP XẾP: TIỀM NĂNG</option><option value="age">SẮP XẾP: MỚI NHẤT</option><option value="liquidity">SẮP XẾP: THANH KHOẢN</option><option value="volume">SẮP XẾP: KHỐI LƯỢNG</option><option value="momentum">SẮP XẾP: ĐỘNG LƯỢNG</option><option value="risk">SẮP XẾP: RỦI RO</option></select><div className="flex items-center gap-2 border border-slate-300 bg-white px-3 h-10"><SlidersHorizontal className="size-4"/><span className="font-mono text-[10px]">CẢNH BÁO ≥</span><input type="number" min="0" max="100" value={threshold} onChange={e => updateThreshold(Number(e.target.value))} className="w-12 font-mono text-xs outline-none"/></div><div className="flex items-center gap-2 border border-cyan-200 bg-cyan-50 px-3 h-10"><Tooltip><TooltipTrigger asChild><button aria-label="Giải thích bộ lọc khối lượng 24 giờ"><Info className="size-3 text-cyan-700"/></button></TooltipTrigger><TooltipContent className="max-w-xs font-mono text-xs">Lọc theo tổng giá trị giao dịch trong 24 giờ qua. Để trống một phía nếu không muốn giới hạn.</TooltipContent></Tooltip><span className="font-mono text-[10px]">KHỐI LƯỢNG 24H $</span><input aria-label="Khối lượng 24 giờ tối thiểu" type="number" min="0" placeholder="tối thiểu" value={minVolume || ""} onChange={e => setMinVolume(Number(e.target.value) || 0)} className="w-16 bg-transparent font-mono text-xs outline-none"/><span className="text-slate-400">—</span><input aria-label="Khối lượng 24 giờ tối đa" type="number" min="0" placeholder="tối đa" value={maxVolume || ""} onChange={e => setMaxVolume(Number(e.target.value) || 0)} className="w-16 bg-transparent font-mono text-xs outline-none"/></div><div className="flex items-center gap-2 border border-slate-300 bg-white px-3 h-10"><span className="font-mono text-[10px]">KHOẢNG GIÁ</span><select aria-label="Khoảng thời gian sparkline" value={sparklineRange} onChange={e => setSparklineRange(e.target.value as typeof sparklineRange)} className="bg-transparent font-mono text-xs outline-none"><option value="1h">1 GIỜ</option><option value="4h">4 GIỜ</option><option value="24h">24 GIỜ</option></select></div></section>
      <div className="grid xl:grid-cols-[1fr_380px] gap-5 items-start"><Card className="rounded-none border-slate-300 shadow-[5px_5px_0_#d9f6fa] overflow-hidden"><CardHeader className="bg-white border-b border-slate-200 py-4"><div className="flex justify-between items-center"><CardTitle className="font-mono text-xs tracking-widest">CÁC CẶP MỚI NHẤT / {query.isFetching ? "ĐANG QUÉT" : "SẴN SÀNG"}</CardTitle><span className="font-mono text-[10px] text-slate-400">NGUỒN: {query.data?.source ?? "—"}</span></div></CardHeader><CardContent className="p-0 overflow-x-auto"><table className="w-full text-left min-w-[900px]"><thead className="bg-slate-50 font-mono text-[10px] uppercase tracking-wider text-slate-500"><tr>{["Mã / chuỗi","Tuổi","Xu hướng 24h","Thanh khoản","KL 24h","Động lượng","Tiềm năng","Rủi ro",""].map(h => <th key={h} className="px-4 py-3 font-normal">{h}</th>)}</tr></thead><tbody>{query.isFetching ? Array.from({ length: 6 }).map((_, index) => <SkeletonRow key={`skeleton-${index}`} />) : tokens.map(token => <tr key={token.id} onClick={() => setSelected(token)} className="border-t border-slate-200 hover:bg-cyan-50/50 cursor-pointer transition-colors"><td className="px-4 py-4"><div className="flex items-center gap-3"><button onClick={e => { e.stopPropagation(); toggleWatch(token.id); }} aria-label="Bật hoặc tắt danh sách theo dõi"><Star className={watchlist.includes(token.id) ? "size-4 fill-pink-400 text-pink-500" : "size-4 text-slate-300"}/></button><div><div className="font-bold">{token.symbol}</div><div className="font-mono text-[10px] text-slate-400">{token.chainName} / {token.dexId}</div></div></div></td><td className="px-4 font-mono text-xs">{ageLabel(token.ageMinutes)}</td><td className="px-2"><Sparkline points={token.sparkline} positive={token.priceChange24h >= 0} freshness={token.freshness} range={sparklineRange}/></td><td className="px-4 font-mono text-xs">${money.format(token.liquidityUsd)}</td><td className="px-4 font-mono text-xs">${money.format(token.volume24h)}</td><td className={`px-4 font-mono text-xs ${token.priceChange24h >= 0 ? "text-emerald-700" : "text-rose-700"}`}>{token.priceChange24h >= 0 ? "+" : ""}{token.priceChange24h.toFixed(1)}%</td><td className="px-4"><span className={`inline-flex border px-2 py-1 font-mono text-xs ${scoreTone(token.potentialScore)}`}>{token.potentialScore}</span></td><td className="px-4"><span className={`inline-flex border px-2 py-1 font-mono text-xs ${scoreTone(token.riskScore, true)}`}>{token.riskScore}</span></td><td className="px-4"><ArrowUpRight className="size-4 text-slate-400"/></td></tr>)}{!query.isFetching && tokens.length === 0 && <tr><td colSpan={9} className="p-16 text-center"><div className="font-mono text-sm">KHÔNG CÓ CẶP PHÙ HỢP</div><p className="font-mono text-xs text-slate-400 mt-2">Hãy xóa bớt bộ lọc hoặc làm mới luồng dữ liệu công khai.</p></td></tr>}</tbody></table></CardContent></Card>
        <aside className="space-y-5">{selected ? <Detail token={selected} onClose={() => setSelected(null)} /> : <Card className="rounded-none border-slate-300 bg-[#fffdf5]"><CardContent className="p-6"><p className="font-mono text-[10px] tracking-widest text-pink-600">CHỌN MỘT CẶP</p><h3 className="text-2xl font-black mt-3">Kiểm tra bằng chứng.</h3><p className="font-mono text-xs leading-5 text-slate-500 mt-3">Mở một dòng để xem cấu thành điểm, lý do rủi ro, chỉ số thị trường và liên kết xác minh bên ngoài.</p><div className="mt-8 h-32 border border-dashed border-slate-300 grid place-items-center"><Activity className="size-8 text-cyan-500"/></div></CardContent></Card>}<Card className="rounded-none border-slate-300"><CardContent className="p-5"><div className="flex items-center gap-2 mb-3"><ShieldAlert className="size-4 text-pink-500"/><p className="font-mono text-xs font-bold">THÔNG BÁO CHỈ NGHIÊN CỨU</p></div><p className="font-mono text-[11px] leading-5 text-slate-500">Điểm số chỉ là tín hiệu sàng lọc, không phải tư vấn tài chính hay cam kết lợi nhuận. Sản phẩm không có mua, bán, ví hoặc thực thi lệnh.</p></CardContent></Card></aside></div>
    </main></div>;
}

function SkeletonRow() { return <tr className="border-t border-slate-200 animate-pulse">{Array.from({ length: 9 }).map((_, i) => <td key={i} className="px-4 py-5"><div className={`h-3 bg-slate-200 ${i === 0 ? "w-24" : "w-14"}`}/></td>)}</tr>; }
function Sparkline({ points, positive, freshness, range: selectedRange }: { points: number[]; positive: boolean; freshness: RadarToken["freshness"]; range: "1h" | "4h" | "24h" }) { const status = points.length < 2 ? "Chưa có dữ liệu OHLCV" : freshness === "fresh" ? "Dữ liệu mới" : freshness === "aging" ? "Dữ liệu đang cũ dần" : "Dữ liệu đã cũ"; if (points.length < 2) return <Tooltip><TooltipTrigger asChild><span className="font-mono text-[9px] text-slate-300 cursor-help">CHƯA CÓ OHLCV <Info className="inline size-3"/></span></TooltipTrigger><TooltipContent className="max-w-xs font-mono text-xs">{status}. OHLCV gồm giá mở cửa, cao nhất, thấp nhất, đóng cửa và khối lượng. Khoảng đang chọn: {selectedRange}.</TooltipContent></Tooltip>; const min = Math.min(...points); const max = Math.max(...points); const valueRange = max - min || 1; const coords = points.map((point, i) => `${(i / (points.length - 1)) * 76 + 2},${28 - ((point - min) / valueRange) * 24}`).join(" "); return <Tooltip><TooltipTrigger asChild><svg width="80" height="32" viewBox="0 0 80 32" role="img" aria-label={`Biểu đồ giá mini ${selectedRange}`}><polyline points={coords} fill="none" stroke={positive ? "#059669" : "#e11d48"} strokeWidth="1.7" vectorEffect="non-scaling-stroke"/><line x1="2" y1="29" x2="78" y2="29" stroke="#cbd5e1" strokeWidth=".6"/></svg></TooltipTrigger><TooltipContent className="font-mono text-xs">{status}. Khoảng: {selectedRange}. Nguồn: nến OHLCV công khai.</TooltipContent></Tooltip>; }
function Stat({ label, value, accent }: { label: string; value: string; accent: string }) { return <div className={`border border-slate-300 bg-white p-4 relative overflow-hidden`}><div className={`absolute top-0 left-0 w-full h-1 bg-${accent === "cyan" ? "cyan" : accent === "pink" ? "pink" : accent === "lime" ? "lime" : "slate"}-300`}/><p className="font-mono text-[10px] text-slate-500 uppercase tracking-wider">{label}</p><p className="text-3xl font-black mt-2">{value}</p></div> }
function Detail({ token, onClose }: { token: RadarToken; onClose: () => void }) { return <Card className="rounded-none border-slate-300"><CardHeader className="border-b border-slate-200"><div className="flex justify-between"><div><p className="font-mono text-[10px] text-slate-400">{token.chainName} / {token.dexId}</p><CardTitle className="text-2xl font-black">{token.symbol}</CardTitle></div><button onClick={onClose} className="font-mono text-xs text-slate-400">ĐÓNG ×</button></div></CardHeader><CardContent className="p-5 space-y-5"><div className="grid grid-cols-2 gap-2"><Score label="Tiềm năng" score={token.potentialScore}/><Score label="Rủi ro" score={token.riskScore} inverse/></div><Metric label="Giá" value={token.priceUsd == null ? "—" : `$${price.format(token.priceUsd)}`}/><Metric label="Thanh khoản" value={`$${money.format(token.liquidityUsd)}`}/><Metric label="Khối lượng 24h" value={`$${money.format(token.volume24h)}`}/><Metric label="Trạng thái dữ liệu" value={`${ageLabel(token.ageMinutes)} / ${token.freshness === "fresh" ? "MỚI" : token.freshness === "aging" ? "ĐANG CŨ DẦN" : "ĐÃ CŨ"}`}/><div><p className="font-mono text-[10px] uppercase text-emerald-700 mb-2">Lý do tiềm năng</p>{token.potentialReasons.map(r => <p key={r} className="font-mono text-[11px] mb-1">+ {r}</p>)}</div><div><p className="font-mono text-[10px] uppercase text-rose-700 mb-2">Lý do rủi ro</p>{token.riskReasons.map(r => <p key={r} className="font-mono text-[11px] mb-1">! {r}</p>)}</div><a href={token.url} target="_blank" rel="noreferrer" className="h-10 border border-slate-950 bg-slate-950 text-white flex items-center justify-center gap-2 font-mono text-xs hover:bg-cyan-600">Xác minh trên trang thị trường <ExternalLink className="size-3"/></a></CardContent></Card> }
function Score({ label, score, inverse = false }: { label: string; score: number; inverse?: boolean }) { return <div className={`border p-3 ${scoreTone(score, inverse)}`}><p className="font-mono text-[10px] uppercase">{label}</p><p className="text-3xl font-black">{score}<span className="text-sm">/100</span></p></div> }
function Metric({ label, value }: { label: string; value: string }) { return <div className="flex justify-between border-b border-slate-100 py-2 font-mono text-xs"><span className="text-slate-500">{label}</span><span>{value}</span></div> }
